{{ include "common.deployment.app" (list . "cockpit-fastapi.deployment") }}

{{- define "cockpit-fastapi.deployment" -}}
spec:
  template:
    spec:
      containers:
        - {{ include "common.container.app" (list . "cockpit-fastapi.fastapi") | nindent 10 }}
        - {{ include "common.container" (list . "cockpit-fastapi.celery") | nindent 10 }}
        - {{ include "cockpit-fastapi.redis" . | nindent 10 }}
      volumes:
        {{- include "__cm_configmount_volumes" . | nindent 6 }}
        - name: redis-data
          emptyDir: {}
{{- end -}}

{{- define "cockpit-fastapi.fastapi" -}}
{{/* Override the path to use for probes. Note that monitoringPort is used by default by common. */}}
livenessProbe:
  httpGet:
    path: /ping
readinessProbe:
  httpGet:
    path: /ping
{{- end -}}

{{- define "cockpit-fastapi.redis" -}}
name: {{ include "common.fullname" . }}-redis
image: {{ include "common.image.from" (list . .Values.redis.image) | replace "@none@/" "" }}
ports:
  - containerPort: 6379
volumeMounts:
  - mountPath: /data
    name: redis-data
{{- end -}}


{{- define "cockpit-fastapi.celery" -}}
{{/*
We need a port here, even though celery doesn't really expose one, to avoid having two pods in the container
defining a "monitoring" port. I tried setting ports: [], but for some reason it doesn't work...
*/}}
ports:
  - containerPort: 55672
name: {{ include "common.fullname" . }}-celery
command: [/docker-entrypoint.sh, celery]
{{- end -}}
