{{- $fastApi := merge .Values.nb_runner.fastapi (pick .Values.nb_runner "image") -}}
{{- $celery := merge .Values.nb_runner.celery (pick .Values.nb_runner "image") -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "nb_runner.labels" (dict "context" .) | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      appName: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations: {{ toYaml .Values.annotations | nindent 8 }}
      labels: {{ include "nb_runner.labels" (dict "context" .) | nindent 8 }}
      name: {{ .Release.Name }}
    spec:
      containers:
        - {{ include "nb_runner.container" (dict "context" . "root" .Values.redis) | nindent 10 }}
        - {{ include "nb_runner.container" (dict "context" . "root" $fastApi) | nindent 10 }}
        - {{ include "nb_runner.container" (dict "context" . "root" $celery) | nindent 10 }}
      volumes: {{ toYaml .Values.volumes | nindent 8 }}
---

{{- define "nb_runner.container" -}}
name: {{ .root.name }}
image: {{ printf "%s:%s" .root.image.name .root.image.tag | quote }}
imagePullPolicy: {{ .root.image.pullPolicy }}
ports:
  - containerPort: {{ .root.port }}
    name: {{ .root.portName | default .root.name  }}
    protocol: {{ default "TCP" .root.portProtocol }}
{{ with .root.command }}command: {{ toYaml . | nindent 2 }}{{ println "" }}{{ end -}}
{{ with .root.livenessProbe }}livenessProbe: {{ toYaml . | nindent 2 }}{{ println "" }}{{ end -}}
{{ with .root.readinessProbe }}readinessProbe: {{ toYaml . | nindent 2 }}{{ println "" }}{{ end -}}
{{ with .root.volumeMounts }}volumeMounts: {{ toYaml . | nindent 2 }}{{ println "" }}{{ end -}}
envFrom:
  {{- if .context.Values.env }}
  - configMapRef:
      name: {{ .context.Release.Name }}
  {{- end }}
  {{- if .context.Values.secrets }}
  - secretRef:
      name: {{ .context.Release.Name }}
  {{- end }}
{{- end -}}
