{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "nb_runner.labels" (dict "context" .) | nindent 4 }}
data:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end -}}
{{- end -}}
