apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "nb_runner.labels" (dict "context" .) | nindent 4 }}
  annotations: {{ toYaml .Values.annotations | nindent 8 }}
spec:
  type: ClusterIP
  selector:
    appName: {{ .Release.Name }}
  ports:
    - name: rest
      port: 8080
      targetPort: {{ .Values.nb_runner.fastapi.portName }}
