redis:
  image:
    project: "@none@" # will be stripped
    name: redis
    tag: latest

common:
  project: llinder

  image:
    name: cockpit-fastapi

  env:
  secretEnv:

  rest:
    enabled: true
